### ISSUE TITLE
Null refences

### ISSUE THREAD

**Issue by eealeivan** [zoetrope/fluent-logger-csharp#2]
Is there any reason why null references are not supported?
I want to log some objects that are not created by myself where null values are totally possible.

**Comment by zoetrope** [comment]
Sorry, It's a documentation miss.
fluent-logger-csharp supporting null reference.

If send a null reference by fluent-logger-csharp, td-agent receive a following message.

  2013-08-08 08:08:08 +0900 test.FluentLoggerSample.Program: {"Level":"DEBUG","Message":{}}
